/*
 * generated by Xtext 2.12.0
 */
package fr.n7.simplepdl.txt.ui;

import com.google.inject.Injector;
import fr.n7.simplepdl.txt.PDL.ui.internal.PDLActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PDLActivator.getInstance().getInjector(PDLActivator.FR_N7_SIMPLEPDL_TXT_PDL);
	}
	
}
