/*
 * generated by Xtext 2.12.0
 */
package fr.n7.simplepdl.txt.ui.tests;

import com.google.inject.Injector;
import fr.n7.simplepdl.txt.PDL.ui.internal.PDLActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PDLActivator.getInstance().getInjector("fr.n7.simplepdl.txt.PDL");
	}

}
